    - name: Deploy VM from Template
      vmware_guest:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_user }}"
        password: "{{ vcenter_pass }}"
        validate_certs: no
        datacenter: "{{ Datacenter }}"
        cluster: "{{ Cluster }}"
        name: "{{ inventory_hostname }}" 
        template: "{{ template }}"
        state: poweredon
        wait_for_ip_address: yes
        networks:
        - name: "{{ portGroup }}"
          type: static
          ip: "{{ ip }}"
          netmask: "{{ mask }}"
          gateway: "{{ gw }}"
          domain: "{{ dom }}"
          dns_servers:
           - "{{ dns_server }}"
        customization:
          hostname: "{{ inventory_hostname }}"
          dns_servers:
           - "{{ dns_server }}"
          domain: "{{ dom }}"
          dns_suffix: "{{ dom }}"
      delegate_to: localhost